Add missing 'vol_diff' key to BinaryPairwiseMeasures.measures_dict
Otherwise, the following KeyError is raised:

Traceback (most recent call last):
  File "/Users/user/code/MetricsReloaded/MetricsReloaded/metrics/pairwise_measures.py", line 1161, in to_dict_meas
    if len(self.measures_dict[key]) == 2:
KeyError: 'vol_diff'